// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from '@rocicorp/zero';
import { createBuilder } from '@rocicorp/zero';

const accountTable = {
	name: 'account',
	columns: {
		id: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		accountId: {
			type: 'string',
			optional: false,
			customType: null as unknown as string,
			serverName: 'account_id'
		},
		providerId: {
			type: 'string',
			optional: false,
			customType: null as unknown as string,
			serverName: 'provider_id'
		},
		userId: {
			type: 'string',
			optional: false,
			customType: null as unknown as string,
			serverName: 'user_id'
		},
		accessToken: {
			type: 'string',
			optional: true,
			customType: null as unknown as string,
			serverName: 'access_token'
		},
		refreshToken: {
			type: 'string',
			optional: true,
			customType: null as unknown as string,
			serverName: 'refresh_token'
		},
		idToken: {
			type: 'string',
			optional: true,
			customType: null as unknown as string,
			serverName: 'id_token'
		},
		accessTokenExpiresAt: {
			type: 'number',
			optional: true,
			customType: null as unknown as number,
			serverName: 'access_token_expires_at'
		},
		refreshTokenExpiresAt: {
			type: 'number',
			optional: true,
			customType: null as unknown as number,
			serverName: 'refresh_token_expires_at'
		},
		scope: {
			type: 'string',
			optional: true,
			customType: null as unknown as string
		},
		password: {
			type: 'string',
			optional: true,
			customType: null as unknown as string
		},
		createdAt: {
			type: 'number',
			optional: false,
			customType: null as unknown as number,
			serverName: 'created_at'
		},
		updatedAt: {
			type: 'number',
			optional: false,
			customType: null as unknown as number,
			serverName: 'updated_at'
		}
	},
	primaryKey: ['id']
} as const;
const awardsTable = {
	name: 'awards',
	columns: {
		id: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		user_id: {
			type: 'string',
			optional: true,
			customType: null as unknown as string
		},
		battle_id: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		award_type: {
			type: 'string',
			optional: false,
			customType: null as unknown as
				| 'MOST_ACCURATE'
				| 'REAL_WORLD'
				| 'BEST_FEEL'
		},
		outcome: {
			type: 'string',
			optional: true,
			customType: null as unknown as 'AWARDED' | 'VOID_TIE' | 'VOID_OTHER'
		},
		created_at: {
			type: 'number',
			optional: true,
			customType: null as unknown as number
		},
		updated_at: {
			type: 'number',
			optional: true,
			customType: null as unknown as number
		}
	},
	primaryKey: ['id']
} as const;
const battleParticipantsTable = {
	name: 'battle_participants',
	columns: {
		id: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		battle_id: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		user_id: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		status: {
			type: 'string',
			optional: true,
			customType: null as unknown as
				| 'PENDING'
				| 'ACTIVE'
				| 'READY'
				| 'DROPPED'
				| 'FINISHED'
		},
		display_order: {
			type: 'number',
			optional: true,
			customType: null as unknown as number
		},
		joined_at: {
			type: 'number',
			optional: true,
			customType: null as unknown as number
		},
		last_seen_at: {
			type: 'number',
			optional: true,
			customType: null as unknown as number
		},
		finished_at: {
			type: 'number',
			optional: true,
			customType: null as unknown as number
		},
		created_at: {
			type: 'number',
			optional: true,
			customType: null as unknown as number
		},
		updated_at: {
			type: 'number',
			optional: true,
			customType: null as unknown as number
		}
	},
	primaryKey: ['id']
} as const;
const battleVotesTable = {
	name: 'battle_votes',
	columns: {
		id: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		battle_id: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		voter_id: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		nominee_hax_id: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		award_type: {
			type: 'string',
			optional: false,
			customType: null as unknown as
				| 'MOST_ACCURATE'
				| 'REAL_WORLD'
				| 'BEST_FEEL'
		},
		locked_at: {
			type: 'number',
			optional: true,
			customType: null as unknown as number
		},
		value: {
			type: 'number',
			optional: false,
			customType: null as unknown as number
		},
		created_at: {
			type: 'number',
			optional: true,
			customType: null as unknown as number
		}
	},
	primaryKey: ['id']
} as const;
const battlesTable = {
	name: 'battles',
	columns: {
		id: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		name: {
			type: 'string',
			optional: true,
			customType: null as unknown as string
		},
		date: {
			type: 'number',
			optional: true,
			customType: null as unknown as number
		},
		referee_id: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		target_id: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		status: {
			type: 'string',
			optional: true,
			customType: null as unknown as 'PENDING' | 'ACTIVE' | 'COMPLETED'
		},
		visibility: {
			type: 'string',
			optional: true,
			customType: null as unknown as 'PUBLIC' | 'PRIVATE'
		},
		zero_room_id: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		type: {
			type: 'string',
			optional: false,
			customType: null as unknown as 'TIME_TRIAL' | 'TIMED_MATCH'
		},
		win_condition: {
			type: 'string',
			optional: true,
			customType: null as unknown as 'VOTING' | 'FIRST_TO_PERFECT'
		},
		total_time_seconds: {
			type: 'number',
			optional: false,
			customType: null as unknown as number
		},
		overtime_seconds: {
			type: 'number',
			optional: true,
			customType: null as unknown as number
		},
		starts_at: {
			type: 'number',
			optional: true,
			customType: null as unknown as number
		},
		ends_at: {
			type: 'number',
			optional: true,
			customType: null as unknown as number
		},
		allow_time_extension: {
			type: 'boolean',
			optional: true,
			customType: null as unknown as boolean
		},
		revealed_at: {
			type: 'number',
			optional: true,
			customType: null as unknown as number
		},
		winner_hax_id: {
			type: 'string',
			optional: true,
			customType: null as unknown as string
		},
		created_at: {
			type: 'number',
			optional: true,
			customType: null as unknown as number
		},
		updated_at: {
			type: 'number',
			optional: true,
			customType: null as unknown as number
		}
	},
	primaryKey: ['id']
} as const;
const haxTable = {
	name: 'hax',
	columns: {
		id: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		target_id: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		battle_id: {
			type: 'string',
			optional: true,
			customType: null as unknown as string
		},
		user_id: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		html: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		css: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		type: {
			type: 'string',
			optional: false,
			customType: null as unknown as 'BATTLE' | 'SOLO'
		},
		submitted_at: {
			type: 'number',
			optional: true,
			customType: null as unknown as number
		},
		submission_locked_at: {
			type: 'number',
			optional: true,
			customType: null as unknown as number
		},
		is_final: {
			type: 'boolean',
			optional: true,
			customType: null as unknown as boolean
		},
		rendered_preview_url: {
			type: 'string',
			optional: true,
			customType: null as unknown as string
		},
		diff_score: {
			type: 'number',
			optional: true,
			customType: null as unknown as number
		},
		diff_score_updated_at: {
			type: 'number',
			optional: true,
			customType: null as unknown as number
		},
		created_at: {
			type: 'number',
			optional: true,
			customType: null as unknown as number
		},
		updated_at: {
			type: 'number',
			optional: true,
			customType: null as unknown as number
		}
	},
	primaryKey: ['id']
} as const;
const haxHistoryTable = {
	name: 'hax_history',
	columns: {
		id: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		hax_id: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		html: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		css: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		elapsed_ms: {
			type: 'number',
			optional: false,
			customType: null as unknown as number
		},
		sequence: {
			type: 'number',
			optional: false,
			customType: null as unknown as number
		},
		created_at: {
			type: 'number',
			optional: true,
			customType: null as unknown as number
		}
	},
	primaryKey: ['id']
} as const;
const imagesTable = {
	name: 'images',
	columns: {
		id: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		key: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		user_id: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		created_at: {
			type: 'number',
			optional: true,
			customType: null as unknown as number
		}
	},
	primaryKey: ['id']
} as const;
const jwksTable = {
	name: 'jwks',
	columns: {
		id: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		publicKey: {
			type: 'string',
			optional: false,
			customType: null as unknown as string,
			serverName: 'public_key'
		},
		privateKey: {
			type: 'string',
			optional: false,
			customType: null as unknown as string,
			serverName: 'private_key'
		},
		createdAt: {
			type: 'number',
			optional: false,
			customType: null as unknown as number,
			serverName: 'created_at'
		}
	},
	primaryKey: ['id']
} as const;
const ratingsTable = {
	name: 'ratings',
	columns: {
		id: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		user_id: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		target_id: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		difficulty: {
			type: 'number',
			optional: false,
			customType: null as unknown as number
		},
		creativity: {
			type: 'number',
			optional: false,
			customType: null as unknown as number
		},
		fun: {
			type: 'number',
			optional: false,
			customType: null as unknown as number
		},
		coolness: {
			type: 'number',
			optional: false,
			customType: null as unknown as number
		},
		created_at: {
			type: 'number',
			optional: true,
			customType: null as unknown as number
		}
	},
	primaryKey: ['id']
} as const;
const sessionTable = {
	name: 'session',
	columns: {
		id: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		expiresAt: {
			type: 'number',
			optional: false,
			customType: null as unknown as number,
			serverName: 'expires_at'
		},
		token: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		createdAt: {
			type: 'number',
			optional: false,
			customType: null as unknown as number,
			serverName: 'created_at'
		},
		updatedAt: {
			type: 'number',
			optional: false,
			customType: null as unknown as number,
			serverName: 'updated_at'
		},
		ipAddress: {
			type: 'string',
			optional: true,
			customType: null as unknown as string,
			serverName: 'ip_address'
		},
		userAgent: {
			type: 'string',
			optional: true,
			customType: null as unknown as string,
			serverName: 'user_agent'
		},
		userId: {
			type: 'string',
			optional: false,
			customType: null as unknown as string,
			serverName: 'user_id'
		},
		impersonatedBy: {
			type: 'string',
			optional: true,
			customType: null as unknown as string,
			serverName: 'impersonated_by'
		}
	},
	primaryKey: ['id']
} as const;
const targetsTable = {
	name: 'targets',
	columns: {
		id: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		name: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		image: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		type: {
			type: 'string',
			optional: false,
			customType: null as unknown as 'CODE' | 'IMAGE' | 'VIDEO'
		},
		inspo: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		created_by: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		is_active: {
			type: 'boolean',
			optional: true,
			customType: null as unknown as boolean
		},
		archived_at: {
			type: 'number',
			optional: true,
			customType: null as unknown as number
		},
		last_updated_at: {
			type: 'number',
			optional: true,
			customType: null as unknown as number
		},
		created_at: {
			type: 'number',
			optional: true,
			customType: null as unknown as number
		},
		updated_at: {
			type: 'number',
			optional: true,
			customType: null as unknown as number
		}
	},
	primaryKey: ['id']
} as const;
const userTable = {
	name: 'user',
	columns: {
		id: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		name: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		username: {
			type: 'string',
			optional: true,
			customType: null as unknown as string
		},
		email: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		emailVerified: {
			type: 'boolean',
			optional: true,
			customType: null as unknown as boolean,
			serverName: 'email_verified'
		},
		image: {
			type: 'string',
			optional: true,
			customType: null as unknown as string
		},
		createdAt: {
			type: 'number',
			optional: true,
			customType: null as unknown as number,
			serverName: 'created_at'
		},
		updatedAt: {
			type: 'number',
			optional: true,
			customType: null as unknown as number,
			serverName: 'updated_at'
		},
		role: {
			type: 'string',
			optional: true,
			customType: null as unknown as string
		},
		banned: {
			type: 'boolean',
			optional: true,
			customType: null as unknown as boolean
		},
		banReason: {
			type: 'string',
			optional: true,
			customType: null as unknown as string,
			serverName: 'ban_reason'
		},
		banExpires: {
			type: 'number',
			optional: true,
			customType: null as unknown as number,
			serverName: 'ban_expires'
		},
		avatar: {
			type: 'string',
			optional: true,
			customType: null as unknown as string
		},
		bio: {
			type: 'string',
			optional: true,
			customType: null as unknown as string
		},
		theme: {
			type: 'string',
			optional: true,
			customType: null as unknown as string
		}
	},
	primaryKey: ['id']
} as const;
const userRelationshipsTable = {
	name: 'user_relationships',
	columns: {
		id: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		user_id: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		related_user_id: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		type: {
			type: 'string',
			optional: false,
			customType: null as unknown as 'FOLLOW' | 'FRIEND'
		},
		created_at: {
			type: 'number',
			optional: true,
			customType: null as unknown as number
		}
	},
	primaryKey: ['id']
} as const;
const verificationTable = {
	name: 'verification',
	columns: {
		id: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		identifier: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		value: {
			type: 'string',
			optional: false,
			customType: null as unknown as string
		},
		expiresAt: {
			type: 'number',
			optional: false,
			customType: null as unknown as number,
			serverName: 'expires_at'
		},
		createdAt: {
			type: 'number',
			optional: true,
			customType: null as unknown as number,
			serverName: 'created_at'
		},
		updatedAt: {
			type: 'number',
			optional: true,
			customType: null as unknown as number,
			serverName: 'updated_at'
		}
	},
	primaryKey: ['id']
} as const;
const battleParticipantsRelationships = {
	battle: [
		{
			sourceField: ['battle_id'],
			destField: ['id'],
			destSchema: 'battles',
			cardinality: 'one'
		}
	],
	user: [
		{
			sourceField: ['user_id'],
			destField: ['id'],
			destSchema: 'user',
			cardinality: 'one'
		}
	],
	hax: [
		{
			sourceField: ['user_id', 'battle_id'],
			destField: ['user_id', 'battle_id'],
			destSchema: 'hax',
			cardinality: 'one'
		}
	]
} as const;
const battlesRelationships = {
	target: [
		{
			sourceField: ['target_id'],
			destField: ['id'],
			destSchema: 'targets',
			cardinality: 'one'
		}
	],
	referee: [
		{
			sourceField: ['referee_id'],
			destField: ['id'],
			destSchema: 'user',
			cardinality: 'one'
		}
	],
	participants: [
		{
			sourceField: ['id'],
			destField: ['battle_id'],
			destSchema: 'battle_participants',
			cardinality: 'many'
		}
	],
	hax: [
		{
			sourceField: ['id'],
			destField: ['battle_id'],
			destSchema: 'hax',
			cardinality: 'many'
		}
	]
} as const;
const battleVotesRelationships = {
	battle: [
		{
			sourceField: ['battle_id'],
			destField: ['id'],
			destSchema: 'battles',
			cardinality: 'one'
		}
	],
	voter: [
		{
			sourceField: ['voter_id'],
			destField: ['id'],
			destSchema: 'user',
			cardinality: 'one'
		}
	],
	nomineeHax: [
		{
			sourceField: ['nominee_hax_id'],
			destField: ['id'],
			destSchema: 'hax',
			cardinality: 'one'
		}
	]
} as const;
const haxHistoryRelationships = {
	hax: [
		{
			sourceField: ['hax_id'],
			destField: ['id'],
			destSchema: 'hax',
			cardinality: 'one'
		}
	]
} as const;
const haxRelationships = {
	user: [
		{
			sourceField: ['user_id'],
			destField: ['id'],
			destSchema: 'user',
			cardinality: 'one'
		}
	],
	battle: [
		{
			sourceField: ['battle_id'],
			destField: ['id'],
			destSchema: 'battles',
			cardinality: 'one'
		}
	],
	target: [
		{
			sourceField: ['target_id'],
			destField: ['id'],
			destSchema: 'targets',
			cardinality: 'one'
		}
	],
	votes: [
		{
			sourceField: ['id'],
			destField: ['nominee_hax_id'],
			destSchema: 'battle_votes',
			cardinality: 'many'
		}
	],
	history: [
		{
			sourceField: ['id'],
			destField: ['hax_id'],
			destSchema: 'hax_history',
			cardinality: 'many'
		}
	]
} as const;
const imagesRelationships = {
	user: [
		{
			sourceField: ['user_id'],
			destField: ['id'],
			destSchema: 'user',
			cardinality: 'one'
		}
	]
} as const;
const ratingsRelationships = {
	user: [
		{
			sourceField: ['user_id'],
			destField: ['id'],
			destSchema: 'user',
			cardinality: 'one'
		}
	],
	target: [
		{
			sourceField: ['target_id'],
			destField: ['id'],
			destSchema: 'targets',
			cardinality: 'one'
		}
	]
} as const;
const targetsRelationships = {
	hax: [
		{
			sourceField: ['id'],
			destField: ['target_id'],
			destSchema: 'hax',
			cardinality: 'many'
		}
	],
	ratings: [
		{
			sourceField: ['id'],
			destField: ['target_id'],
			destSchema: 'ratings',
			cardinality: 'many'
		}
	],
	battles: [
		{
			sourceField: ['id'],
			destField: ['target_id'],
			destSchema: 'battles',
			cardinality: 'many'
		}
	]
} as const;
const userRelationships = {
	relationships: [
		{
			sourceField: ['id'],
			destField: ['user_id'],
			destSchema: 'user_relationships',
			cardinality: 'many'
		}
	],
	relatedRelationships: [
		{
			sourceField: ['id'],
			destField: ['related_user_id'],
			destSchema: 'user_relationships',
			cardinality: 'many'
		}
	],
	participants: [
		{
			sourceField: ['id'],
			destField: ['user_id'],
			destSchema: 'battle_participants',
			cardinality: 'many'
		}
	],
	hax: [
		{
			sourceField: ['id'],
			destField: ['user_id'],
			destSchema: 'hax',
			cardinality: 'many'
		}
	]
} as const;
const userRelationships2 = {
	user: [
		{
			sourceField: ['user_id'],
			destField: ['id'],
			destSchema: 'user',
			cardinality: 'one'
		}
	],
	relatedUser: [
		{
			sourceField: ['related_user_id'],
			destField: ['id'],
			destSchema: 'user',
			cardinality: 'one'
		}
	]
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
	tables: {
		account: accountTable,
		awards: awardsTable,
		battle_participants: battleParticipantsTable,
		battle_votes: battleVotesTable,
		battles: battlesTable,
		hax: haxTable,
		hax_history: haxHistoryTable,
		images: imagesTable,
		jwks: jwksTable,
		ratings: ratingsTable,
		session: sessionTable,
		targets: targetsTable,
		user: userTable,
		user_relationships: userRelationshipsTable,
		verification: verificationTable
	},
	relationships: {
		battle_participants: battleParticipantsRelationships,
		battles: battlesRelationships,
		battle_votes: battleVotesRelationships,
		hax_history: haxHistoryRelationships,
		hax: haxRelationships,
		images: imagesRelationships,
		ratings: ratingsRelationships,
		targets: targetsRelationships,
		user: userRelationships,
		user_relationships: userRelationships2
	},
	enableLegacyQueries: false,
	enableLegacyMutators: false
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "account" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["account"] instead from "@rocicorp/zero".
 */
export type Account = Row['account'];
/**
 * Represents a row from the "awards" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["awards"] instead from "@rocicorp/zero".
 */
export type Award = Row['awards'];
/**
 * Represents a row from the "battle_participants" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["battle_participants"] instead from "@rocicorp/zero".
 */
export type BattleParticipant = Row['battle_participants'];
/**
 * Represents a row from the "battle_votes" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["battle_votes"] instead from "@rocicorp/zero".
 */
export type BattleVote = Row['battle_votes'];
/**
 * Represents a row from the "battles" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["battles"] instead from "@rocicorp/zero".
 */
export type Battle = Row['battles'];
/**
 * Represents a row from the "hax" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["hax"] instead from "@rocicorp/zero".
 */
export type Hax = Row['hax'];
/**
 * Represents a row from the "hax_history" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["hax_history"] instead from "@rocicorp/zero".
 */
export type HaxHistory = Row['hax_history'];
/**
 * Represents a row from the "images" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["images"] instead from "@rocicorp/zero".
 */
export type Image = Row['images'];
/**
 * Represents a row from the "jwks" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["jwks"] instead from "@rocicorp/zero".
 */
export type Jwk = Row['jwks'];
/**
 * Represents a row from the "ratings" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["ratings"] instead from "@rocicorp/zero".
 */
export type Rating = Row['ratings'];
/**
 * Represents a row from the "session" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["session"] instead from "@rocicorp/zero".
 */
export type Session = Row['session'];
/**
 * Represents a row from the "targets" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["targets"] instead from "@rocicorp/zero".
 */
export type Target = Row['targets'];
/**
 * Represents a row from the "user" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["user"] instead from "@rocicorp/zero".
 */
export type User = Row['user'];
/**
 * Represents a row from the "user_relationships" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["user_relationships"] instead from "@rocicorp/zero".
 */
export type UserRelationship = Row['user_relationships'];
/**
 * Represents a row from the "verification" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["verification"] instead from "@rocicorp/zero".
 */
export type Verification = Row['verification'];

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use `zql` instead.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module '@rocicorp/zero' {
	interface DefaultTypes {
		schema: Schema;
	}
}
