name = "synhax"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-09-10"
compatibility_flags = ["nodejs_compat"]
keep_vars = true

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"


[[hyperdrive]]
binding = "HYPERDRIVE"
id = "7b4ec959f560438b92c0b0e5c90bd59b"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
