name = "synhax"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-09-10"
compatibility_flags = ["nodejs_compat"]
keep_vars = true

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"


[[hyperdrive]]
binding = "HYPERDRIVE"
id = "84259142fc264c3b9aba32a4701615d7"
localConnectionString = "postgresql://postgres:password@127.0.0.1/synhax"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
